#!/bin/bash -l 
#SBATCH --time=48:00:00
#SBATCH --ntasks=10
#SBATCH --tmp=10g
#SBATCH --mem=10g
#SBATCH --mail-type=ALL
#SBATCH --mail-user=jaber038@umn.edu
#SBATCH -p small,large,amdlarge,amdsmall 

source /etc/profile.d/modules.sh 
module load impi 
module load R/4.1.0 

conda activate ruv
python3 main.py
